version: '2'
services:
  brackets:
    build:
      context: .
      dockerfile: dockerfiles/brackets.dockerfile
    image: brackets:latest
    ports:
      - "8000:8000"

  postgresql:
    build:
      context: .
      dockerfile: dockerfiles/postgresql.dockerfile
    image: thimble-postgresql:latest
    ports:
      - "5432:5432"

  publish:
    build:
      context: .
      dockerfile: dockerfiles/publish.dockerfile
    image: publish:latest
    env_file: ./envfiles/publish.env
    ports:
      - "8001:8001"
      - "2016:2016"
    # depends_on:
    #   - postgresql

  id:
    build:
      context: .
      dockerfile: dockerfiles/id.dockerfile
    image: id-webmaker:latest
    ports:
      - "1234:1234"
      # depends_on:
      #   - postgresql
      #   - publish

  login:
    build:
      context: .
      dockerfile: dockerfiles/login.dockerfile
    image: login-webmaker:latest
    ports:
      - "3000:3000"
      # depends_on:
      #   - id

  thimble:
    build:
      context: .
      dockerfile: dockerfiles/thimble.dockerfile
    image: thimble:latest
    ports:
      - "3500:3500"
